filebeat.inputs:
  - type: filestream
    id: wazuh-alerts
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json
    parsers:
      - ndjson:
          target: ""
          add_error_key: true

processors:
  - add_host_metadata: ~

setup.template.enabled: false
setup.ilm.enabled: false
 

output.elasticsearch:
  hosts: ["http://opensearch:9200"]
  allow_older_versions: true
  index: "wazuh-alerts-%{+yyyy.MM.dd}"
  
