[SERVICE]
    Flush         1
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Tag               wazuh.alerts
    Path              /var/ossec/logs/alerts/alerts.json
    Parser            json
    Refresh_Interval  2
    Read_From_Head    On

[OUTPUT]
    Name            opensearch
    Match           wazuh.alerts
    Host            opensearch
    Port            9200
    Index           wazuh-alerts-%Y.%m.%d
    TLS             Off
    Suppress_Type_Name On
