global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['minisoc-alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'minisoc-backend'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['nestjs-api:4000']
    scrape_interval: 10s

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['minisoc-alertmanager:9093']
