# ============================================================
# Configuration TheHive 5 - Mini-SOC
# ============================================================

# Emplacement des fichiers et données
storage {
  provider = localfs
  localfs.location = "/opt/thp/thehive/data"
}

# Configuration de la recherche (OpenSearch)
db.janusgraph.index.search {
  backend = elasticsearch
  hostname = ["opensearch:9200"]
  index-name = thehive
  elasticsearch {
    ssl.enabled = false
  }
}

# Intégration Cortex
cortex {
  servers = [
    {
      name = "MiniSOC-Cortex"
      url = "http://cortex:9001"
      auth {
        type = "bearer"
        key = "${?CORTEX_API_KEY}"
      }
    }
  ]
}

# Intégration MISP
misp {
  servers = [
    {
      name = "MiniSOC-MISP"
      url = "http://misp:80"
      auth {
        type = "key"
        key = "${?MISP_API_KEY}"
      }
    }
  ]
}