# Configuration de la recherche (Pointant vers le conteneur OpenSearch)
search {
  provider = "elasticsearch"
  uri = "http://opensearch:9200"
}

# Désactivation du téléchargement automatique des analyseurs/répondeurs distants
analyzer.urls = []
responder.urls = []

# (Optionnel) Si OpenSearch requiert une authentification basique
# search.basicAuth.username = "admin"
# search.basicAuth.password = "admin"