# Configuration globale de la recherche (Elasticsearch / OpenSearch)
search {
  host = ["opensearch:9200"]
  protocol = "http"
}

# (Optionnel) Désactivation du téléchargement automatique si pas d'accès Internet direct
# analyzer.urls = []
# responder.urls = []