search {
  provider = "elasticsearch"
  uri = "http://opensearch:9200"
  index = "cortex"
  autoCreateIndex = true
}

analyzer {
  urls = [
    "https://cortex-utils.thehive-project.org/analyzers.json"
  ]
  # Ou pour la lecture locale des répertoires :
  path = [
    "/opt/cortex/analyzers"
  ]
}

responder {
  urls = [
    "/opt/cortex/analyzers/*"
  ]
}

job {
  runner = [docker]
  docker {
    jobDirectory = "/tmp/cortex-jobs"
  }
}
