---
all:
  vars:
    ansible_user: deploy
    ansible_ssh_private_key_file: ~/.ssh/minisoc_deploy
    ansible_python_interpreter: /usr/bin/python3

  children:
    managers:
      hosts:
        soc-manager-01:
          ansible_host: 10.0.1.10
          role: wazuh_manager

    workers:
      hosts:
        soc-worker-01:
          ansible_host: 10.0.1.11
        soc-worker-02:
          ansible_host: 10.0.1.12

    monitoring:
      hosts:
        soc-monitor-01:
          ansible_host: 10.0.1.20

    databases:
      hosts:
        soc-db-01:
          ansible_host: 10.0.1.30
          role: primary
        soc-db-02:
          ansible_host: 10.0.1.31
          role: replica