apiVersion: v1
kind: Secret
metadata:
  name: minisoc-secrets
  namespace: minisoc
type: Opaque
data:
  # Base64 encoded - remplacer par de vraies valeurs
  database-url: cG9zdGdyZXNxbDovL21pbmlzb2M6c2VjcmV0QHBvc3RncmVzOjU0MzIvbWluaXNvYw==
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktY2hhbmdlLW1l
  redis-url: cmVkaXM6Ly86cGFzc3dvcmRAcmVkaXM6NjM3OQ==
